#!/bin/bash

# Directory containing allc files for each sample
input_dir=$1 
outdir=$2
nproc=8

genebody=/cndd/projects/Public_Datasets/references/hg19/transcriptome/gencode.v19.annotation_genes_mypy.tsv

#for f in $input_dir/*_bismark; do

# sample=`basename $f`;
# sample=${sample%_bismark}
#
 echo "Processing $sample"

 # Run tabix indexing if not done already. Use maximum of nproc processors
# ls $f/allc_*.tsv.gz | xargs --max-procs=$nproc -I{} allc_tabix {}

 # Step 1: gene-body methylation
# mc_gene_level.py ${f%_bismark} $genebody $outdir

#done

find $input_dir -type d -name '*_bismark' | xargs -I{} -P$nproc ./mc_gene_level.py {} --genebody=$genebody --outdir=$outdir
